### ISSUE TITLE
Error - hashes do not match for v2.14.2.1

### ISSUE THREAD

**Issue by recumbent** [dittodhole/chocolatey-rescuetime#5]
Error - hashes do not match. Actual value was '219D51612ADE81777A1E01B3A33BFE95B32AD425'.
ERROR: Checksum for 'C:\Users\james.murphy\AppData\Local\Temp\chocolatey\rescuetime\2.14.2.1\RescueTimeInstaller.exe' did not meet '0b58502d86c89ccf113ae81a7816bbe28887722d' for checksum type 'sha1'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.

One assumes that the installer has been updated and indeed the version listed on the [download page](https://www.rescuetime.com/get_rescuetime) - at time of typing - is Version: 2.14.4.2

**Comment by dittodhole** [comment]
This was reported a while ago via http://disq.us/p/1y8r5d8
Got resolved with 4b22295d2656ba187e7c651d9c76739a0c343e5f which I will merge within the next minutes, as I was waiting for a new version of RescueTime being released (you can't update an existing versions when it  is approved).

Thanks for bringing this to my attention!

**Comment by dittodhole** [comment]
New release was submitted https://chocolatey.org/packages/rescuetime/2.14.4.2
